### ISSUE TITLE
While Using Group Chat the First logged in user is not getting connected to friendlist of any other user

### ISSUE THREAD

**Issue by Code-N-K** [rpaschoal/ng-chat-netcoreapp#4]
Your SignalR Group chat example with group using SignalRGroup adapter is not adding the second user details in friend list, If two users are connected friendlist only shows one user 
<img width="943" alt="groupExample" src="https://user-images.githubusercontent.com/21154957/55710788-006f2400-5a09-11e9-94b0-7e8211267a44.png">
@rpaschoal

**Comment by rpaschoal** [comment]
Hi @Code-N-K ,

Is your fork up to date with master? I've pushed some code yesterday to it as I've realized I had some code still sitting on my local machine. Seems to be working just fine here for me: https://ng-chat.azurewebsites.net/

**Comment by Code-N-K** [comment]
As i am doing this in SignalR not in AzureSignalR. 

In native SignalR, While Using Group Chat HUB the First logged in user is not getting connected/displayed to friendlist of any other user.

While the same is working for SignalR, Chat HUB. @rpaschoal
